### PR TITLE
Vignette checks

### PR DESCRIPTION
**Pull request by cimentadaj**
Let's see how it renders on the website.

### CODE REVIEW

**Comment by cimentadaj** [comment]
Gentler reminder -- need to send this to Patrickkkk.

**Comment by timriffe** [comment]
unit tests throw error: `test-API.R#28`

**Comment by cimentadaj** [comment]
It seems the API is down :/. I'll send a new PR commenting tests out.

**Comment by cimentadaj** [comment]
Actually, this will have to wait because the vignette can't be compiled (no API), so there's no point in commenting out the tests. Sending an email to Dennis now.

**Pull request merged**
