### PR TITLE
DDSQLtools v0.0.2 - Contains wrap functions for age-splitting and heaping methods

### PR DESCRIPTION
**Pull request by mpascariu**
Everything works fine. Data, examples included.

Thanks.
Marius

### CODE REVIEW

**Review by timriffe — APPROVED** [review]
this appears as we discussed in call last week. Notes: some parts of this wrapper may be modularized later (population columns in a utils.R file). Minor foreseen issues in real life application: -1 span can be found in both old open age, but also at age 0 open age for total, so isOAG() should be aware of that if it isn't already. Not an issue with package data, but would be issue w demodata downstream. Open question as to how and in which column to record that the result came from this wrapper, particular demotools functions & args & version, etc-- i.e. breadcrumb trail.

**Review by timriffe — APPROVED** [review]
ahh, now on next commit and liking this. formatOutputTable() looks good. Imagining it would be cool to pass in the function call that invokes it and save as string in a column. But even so that'd be a partial solution to producing a reproducibility path. I see is.OAG() is updated, good. Approving. Will now look at ageMax, ageMin to make consistent in DemoTools

**Comment by mpascariu** [comment]
To record that the result came from a particular wrapper I used the columns `DataProcess` and `DataProcessType` (already implemented). We can write the `DDSQLtools` call function in one of the columns and the `DemoTools` function name in the other or any other code if there are specific requirements.

**Comment by mpascariu** [comment]
Please prepare for me another list of functions to work on on Friday and maybe over the weekend between BBQs. Thanks.

**Comment by timriffe** [comment]
Thanks MP,
1) add evaluation functions in the script AGESEX.R to the list of stats produced by your age heaping wrapper. Some of these are more than age heaping, but there are are further ones.
2) produce a DDSQLtools way to call agesmth(), added today to DemoTools. It presently can call 5 methods, and I'm working to add 1-3 more. AFAIK all 5 methods have standard args and output, but I do appreciate if you note deviations in need of attention. 
Looking good on the DDSQLtools side of things

**Pull request merged**
