### PR TITLE
A general revamp of dependencies

### PR DESCRIPTION
**Pull request by cimentadaj**
This one should be much clearer. The PR takes care of:

* Fixing undefined symbols by eliminating `mutate` calls and using `within` from `base`.
* Harmonizes the `law` argument
* Organize/remove dependencies when possible: this means removing most dependencies from `importFrom` and only relying on `DESCRIPTION`.

All checks pass + travis is good to do.

### CODE REVIEW

**Review by timriffe — APPROVED** [review]
questions: 
1) how does `within()` get rid of the visible bindings warnings?
2) was Rdpack simply not being used before? In `DemoTools` we use it as the reference compiler for roxygen+help files.

**Comment by cimentadaj** [comment]
1. Because all variable definitions are happening inside an expression and R CMD check is smart enough to know that they're being defined there. For `mutate`, there's really no way of knowing that since they "look" like variables being referenced outside of the `mutate` call but really they just "look" like it because of non-standard evaluation. In fact, they came up with a solution with `rlang` of [introducing a new](https://www.tidyverse.org/blog/2018/10/rlang-0-3-0/) `.data` argument so that columns can be referenced with `.data` and R CMD check is not fooled.

2. I'm not sure where it's being used but I haven't seen it anywhere and every passes without it. How do you use it in `DemoTools`? I really don't know what the pkg does.

**Comment by timriffe** [comment]
1) in `DemoTools` we have this situation with the new migration functions,
and I decided to deal with it using the `rlang` `!!sym(varname)` idiom.
`rlang` has no dependencies of its own, so I considered it acceptable. The
heaviest dependency load in `DemoTools` is coming from `ungroup`, and I
don't know what to do about it.

2) look at [check_heaping](
https://github.com/timriffe/DemoTools/blob/master/R/check_heaping.R)
`\insertRef{}` handles bibtex tags in `@references`, and `REFERENCES.bib`
lives in `/inst/`

**Comment by cimentadaj** [comment]
1. Hmm, I see. 

2. I have an issue in my fork to remind me to check the docs in detail. From a simple search there isn't anything like this ins DDSQLtools so far but I'll keep in mind for when updating the docs. Maybe I'll have to insert these references and add it back to the pkg.

**Pull request merged**
